In [226]:
import pandas as pd
from tqdm import tqdm
import json
import numpy as np

import pycountry_convert as pc

In [227]:
profiles = pd.read_json("D:\Projects\Big data storage and processing\IT4043E_Group15_Problem1\output\profiles.json")
profiles = profiles.transpose()
idxs = [i for i in range(2150)]
profiles.index = idxs
profiles.head()

,user,follower,following,tweet
0,"{'id': 2862957343, 'id_str': '2862957343', 'ur...","[{'id': 1700886965070209024, 'id_str': '170088...","[{'id': 241664456, 'id_str': '241664456', 'url...","[{'id': 1725519432179482712, 'id_str': '172551..."
1,"{'id': 1001220565510836224, 'id_str': '1001220...","[{'id': 717926102614716417, 'id_str': '7179261...","[{'id': 717926102614716417, 'id_str': '7179261...","[{'id': 1719755963572305923, 'id_str': '171975..."
2,"{'id': 1431618946478665744, 'id_str': '1431618...","[{'id': 1388082417525686277, 'id_str': '138808...","[{'id': 1373920301516394498, 'id_str': '137392...","[{'id': 1725518158356951511, 'id_str': '172551..."
3,"{'id': 12361952, 'id_str': '12361952', 'url': ...","[{'id': 6635012, 'id_str': '6635012', 'url': '...","[{'id': 3285797414, 'id_str': '3285797414', 'u...",[]
4,"{'id': 1563736124052443136, 'id_str': '1563736...","[{'id': 1716622096514863104, 'id_str': '171662...","[{'id': 1357767155786395653, 'id_str': '135776...","[{'id': 1723335569470836938, 'id_str': '172333..."

In [228]:
users = []
for user in profiles["user"]:
    users.append(user)
users = pd.DataFrame.from_records(users, index=profiles.index)
users.head()

,id,id_str,url,username,displayname,rawDescription,created,followersCount,friendsCount,statusesCount,...,mediaCount,location,profileImageUrl,profileBannerUrl,protected,verified,blue,blueType,descriptionLinks,_type
0,2.862957e+09,2862957343,https://twitter.com/Day_trading247,Day_trading247,Day Trading BTC SignalüìàüìâüìäüíµüèÖ,"Making your dream come through in day trading,...",2014-10-18 15:45:57+00:00,868.0,4.0,4140.0,...,1315.0,,https://pbs.twimg.com/profile_images/171298479...,https://pbs.twimg.com/profile_banners/28629573...,NaN,False,True,None,"[{'url': 'https://t.me/D_tradesignal', 'text':...",snscrape.modules.twitter.User
1,1.001221e+18,1001220565510836224,https://twitter.com/samuelarmes,samuelarmes,Samuel Armes (Florida Blockchain Business Assoc.),Surf maxi üåä and Founder of FBBA‚ÄîFlorida's Larg...,2018-05-28 21:55:59+00:00,2017.0,465.0,1234.0,...,129.0,"Florida, USA",https://pbs.twimg.com/profile_images/167447729...,https://pbs.twimg.com/profile_banners/10012205...,NaN,False,True,None,"[{'url': 'https://linktr.ee/samuelarmes', 'tex...",snscrape.modules.twitter.User
2,1.431619e+18,1431618946478665744,https://twitter.com/nft_polka,nft_polka,hati (.CLOSEPA),È≠îÁïå„Å´ÁÑº„Åã„Çå„Å™„Åå„ÇâÊ•Ω„Åó„Çì„Åß„ÅÑ„Åæ„Åôüî•Èõ£„Åó„ÅÑ‰∫ã„ÅØÊäú„Åç„Å´„Åó„Å¶Twitter„ÇÇ„ÇÜ„Çã„ÇÜ„Çã„Å®„ÄÇ„Ç¨„ÉÅ„Éõ„Å®„ÅÑ...,2021-08-28 14:05:45+00:00,544.0,558.0,1859.0,...,103.0,Êó•Êú¨,https://pbs.twimg.com/profile_images/162795117...,https://pbs.twimg.com/profile_banners/14316189...,NaN,False,False,None,[],snscrape.modules.twitter.User
3,1.236195e+07,12361952,https://twitter.com/jsadlowe,jsadlowe,Jonathan Sadlowe,General Partner @gossamercap Previously CMO @s...,2008-01-17 15:55:35+00:00,1019.0,636.0,2678.0,...,131.0,CO,https://pbs.twimg.com/profile_images/171410676...,https://pbs.twimg.com/profile_banners/12361952...,NaN,False,True,None,"[{'url': 'http://jonathansadlowe.com', 'text':...",snscrape.modules.twitter.User
4,1.563736e+18,1563736124052443136,https://twitter.com/ibneAbbasss,ibneAbbasss,Ibn e Abbas,Hello! This is Ibne Abbas. The Trader.\n\n Tra...,2022-08-28 03:52:23+00:00,22.0,41.0,61.0,...,30.0,,https://pbs.twimg.com/profile_images/172433546...,https://pbs.twimg.com/profile_banners/15637361...,NaN,False,False,None,[],snscrape.modules.twitter.User

In [229]:
unnecessary = ['profileImageUrl','profileBannerUrl','descriptionLinks','_type','id_str','url','created', 
               'rawDescription', 'protected', 'blueType', 'displayname']
users_dropped = users.drop(columns=unnecessary, axis=1)
users_dropped.head()

,id,username,followersCount,friendsCount,statusesCount,favouritesCount,listedCount,mediaCount,location,verified,blue
0,2.862957e+09,Day_trading247,868.0,4.0,4140.0,11.0,2.0,1315.0,,False,True
1,1.001221e+18,samuelarmes,2017.0,465.0,1234.0,3890.0,17.0,129.0,"Florida, USA",False,True
2,1.431619e+18,nft_polka,544.0,558.0,1859.0,1961.0,20.0,103.0,Êó•Êú¨,False,False
3,1.236195e+07,jsadlowe,1019.0,636.0,2678.0,7415.0,23.0,131.0,CO,False,True
4,1.563736e+18,ibneAbbasss,22.0,41.0,61.0,67.0,0.0,30.0,,False,False

In [230]:
users_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2150 entries, 0 to 2149
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2149 non-null   float64
 1   username         2149 non-null   object
 2   followersCount   2149 non-null   float64
 3   friendsCount     2149 non-null   float64
 4   statusesCount    2149 non-null   float64
 5   favouritesCount  2149 non-null   float64
 6   listedCount      2149 non-null   float64
 7   mediaCount       2149 non-null   float64
 8   location         2149 non-null   object
 9   verified         2149 non-null   object
 10  blue             2149 non-null   object
dtypes: float64(7), object(4)
memory usage: 201.6+ KB

In [231]:
tweets = []
for twt_lst in profiles['tweet']:
    for tweet in twt_lst:
        tweets.append(tweet)
tweets = pd.DataFrame.from_records(tweets)
tweets.head()

,id,id_str,url,date,user,lang,rawContent,replyCount,retweetCount,likeCount,...,quotedTweet,place,coordinates,inReplyToTweetId,inReplyToUser,source,sourceUrl,sourceLabel,media,_type
0,1725519432179482712,1725519432179482712,https://twitter.com/Day_trading247/status/1725...,2023-11-17 14:21:05+00:00,"{'id': 2862957343, 'id_str': '2862957343', 'ur...",en,#Bitcoin and Justice for all. https://t.co/Jyf...,1,0,0,...,None,None,None,NaN,None,"<a href=""https://ifttt.com"" rel=""nofollow"">IFT...",https://ifttt.com,IFTTT,{'photos': [{'url': 'https://pbs.twimg.com/med...,snscrape.modules.twitter.Tweet
1,1725516970643095864,1725516970643095864,https://twitter.com/Day_trading247/status/1725...,2023-11-17 14:11:19+00:00,"{'id': 2862957343, 'id_str': '2862957343', 'ur...",en,seth_fin: üå±üå±üå±üå±üíµüíµüíµüíµ\n#Bitcoin illiquid supply k...,0,0,0,...,None,None,None,NaN,None,"<a href=""https://ifttt.com"" rel=""nofollow"">IFT...",https://ifttt.com,IFTTT,{'photos': [{'url': 'https://pbs.twimg.com/med...,snscrape.modules.twitter.Tweet
2,1725509355741573540,1725509355741573540,https://twitter.com/Day_trading247/status/1725...,2023-11-17 13:41:03+00:00,"{'id': 2862957343, 'id_str': '2862957343', 'ur...",en,seth_fin: @FrankLambeek @davidgokhshtein @Kyle...,0,0,1,...,None,None,None,NaN,None,"<a href=""https://ifttt.com"" rel=""nofollow"">IFT...",https://ifttt.com,IFTTT,"{'photos': [], 'videos': [], 'animated': []}",snscrape.modules.twitter.Tweet
3,1725509353032101920,1725509353032101920,https://twitter.com/Day_trading247/status/1725...,2023-11-17 13:41:02+00:00,"{'id': 2862957343, 'id_str': '2862957343', 'ur...",en,seth_fin: RT @seth_fin: üö® BREAKING NEWS üö® \n\n...,0,0,0,...,None,None,None,NaN,None,"<a href=""https://ifttt.com"" rel=""nofollow"">IFT...",https://ifttt.com,IFTTT,"{'photos': [], 'videos': [], 'animated': []}",snscrape.modules.twitter.Tweet
4,1725499715519664483,1725499715519664483,https://twitter.com/Day_trading247/status/1725...,2023-11-17 13:02:45+00:00,"{'id': 2862957343, 'id_str': '2862957343', 'ur...",en,Sell all your chairs. #BTC https://t.co/xwcAdz...,2,0,0,...,None,None,None,NaN,None,"<a href=""https://ifttt.com"" rel=""nofollow"">IFT...",https://ifttt.com,IFTTT,{'photos': [{'url': 'https://pbs.twimg.com/med...,snscrape.modules.twitter.Tweet

In [232]:
tweets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74008 entries, 0 to 74007
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                74008 non-null  int64
 1   id_str            74008 non-null  object
 2   url               74008 non-null  object
 3   date              74008 non-null  object
 4   user              74008 non-null  object
 5   lang              74008 non-null  object
 6   rawContent        74008 non-null  object
 7   replyCount        74008 non-null  int64
 8   retweetCount      74008 non-null  int64
 9   likeCount         74008 non-null  int64
 10  quoteCount        74008 non-null  int64
 11  conversationId    74008 non-null  int64
 12  hashtags          74008 non-null  object
 13  cashtags          74008 non-null  object
 14  mentionedUsers    74008 non-null  object
 15  links             74008 non-null  object
 16  viewCount         72036 non-null  float64
 17  retweetedTweet    17365 non-null  object
 18  quotedTweet       10163 non-null  object
 19  place             386 non-null    object
 20  coordinates       0 non-null      object
 21  inReplyToTweetId  5113 non-null   float64
 22  inReplyToUser     5334 non-null   object
 23  source            74008 non-null  object
 24  sourceUrl         74008 non-null  object
 25  sourceLabel       74008 non-null  object
 26  media             74008 non-null  object
 27  _type             74008 non-null  object
dtypes: float64(2), int64(6), object(20)
memory usage: 15.8+ MB

In [233]:
tweets["user"] = tweets["user"].map(lambda x: x["id"])
tweets_dropped = tweets[["id", "user", "replyCount", "retweetCount", 
                         "likeCount", "quoteCount", "viewCount"]]
tweets_dropped.rename(columns={"user": "user_id"}, inplace=True)
tweets_dropped.head()

C:\Users\nguye\AppData\Local\Temp\ipykernel_15160\3443615195.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets_dropped.rename(columns={"user": "user_id"}, inplace=True)

,id,user_id,replyCount,retweetCount,likeCount,quoteCount,viewCount
0,1725519432179482712,2862957343,1,0,0,0,16.0
1,1725516970643095864,2862957343,0,0,0,0,15.0
2,1725509355741573540,2862957343,0,0,1,0,7.0
3,1725509353032101920,2862957343,0,0,0,0,9.0
4,1725499715519664483,2862957343,2,0,0,0,9.0

In [234]:
with open('D:\Projects\Big data storage and processing\IT4043E_Group15_Problem1\output\location.json') as json_file:
    location_dict = json.load(json_file)
for k, v in location_dict.items():
    if v == "None":
        location_dict[k] = None
location_dict

{'location': None,
 'Florida, USA': ' United States',
 'Êó•Êú¨': 'Japan',
 'CO': ' Italy',
 'Sandbanks, UK': ' United Kingdom',
 'El Trapiche': ' Venezuela',
 'TADC': None,
 'Moon': ' Estonia',
 'Earth': ' United States',
 'Vi·ªát Nam': 'Vietnam',
 'Belgique': 'Belgium',
 'Global': ' Canada',
 'On-Chain': ' Canada',
 'New York, USA': ' United States',
 'Delta, Nigeria': ' Nigeria',
 'Canada': 'Canada',
 'Porto, Portugal': ' Portugal',
 'Serengeti-Mara': ' Tanzania',
 'ordiverse': None,
 'https://instagram.com/birdbird': None,
 'Switzerland': 'Switzerland',
 '@ArtStyleWorldüèÜ Mimi Teamüíû': None,
 'CryptoTribune': None,
 'UK': ' Central African Republic',
 'Minnesota': ' United States',
 'Sebuleni': None,
 'Amsterdam, Niederlande': ' Netherlands',
 'X': ' Argentina',
 'Metaverse': ' United States',
 'Internet': ' United States',
 'WorldWide': ' Australia',
 'WEB3': ' Kazakhstan',
 'ŒïŒªŒªŒ¨œÇ': 'Greece',
 'Republic of the Philippines': 'Philippines',
 'Miami, FL': ' United States',
 'DeCentralized': ' Greece',
 'Alg√©rie': 'Algeria',
 'United States': 'United States',
 'North West, England': ' United Kingdom',
 ' Lincoln, AL ': ' United States',
 'YKÂ∏Ç„Ç¢„É¨„Ç≠Ê≤º': None,
 'Blockchain': ' Ukraine',
 'UNN': ' Norway',
 'Los Angeles, Ca': ' United States',
 '‡¥ï‡µá‡¥∞‡¥≥‡¥Ç, ‡§≠‡§æ‡§∞‡§§‡§Ç': ' India',
 'Asni√®res (92), France': ' France',
 'The Interchain Ecosystem ‚öõÔ∏è': None,
 'Chu·ªìng g√† #CSM ': None,
 'United Kingdom': 'United Kingdom',
 'Nova Campinas, Duq Caxias - RJ': None,
 'Orange Coin': ' United States',
 'Colombia': 'Colombia',
 'Singapore': 'Singapore',
 'Planet Earth': ' United States',
 'San Diego': ' United States',
 'Black Blockchain': None,
 'Mars moor üá≤üá¶‚ò™Ô∏èü™∂': None,
 'CyberVerse': None,
 ' Grosse Pointe Woods, MI': ' United States',
 'OgiFAM': None,
 'Indonesia': 'Indonesia',
 'Bucharest, Romania': ' Romania',
 'Orlando, FL': ' United States',
 'Kano': ' Nigeria',
 'North Carolina, USA': ' United States',
 'Isekai-desu': None,
 'Malayisa': None,
 'Âè∞ÁÅ£': 'Taiwan',
 'Montr√©al, Qu√©bec': ' Canada',
 'Nigeria': 'Nigeria',
 'Memeland': None,
 'Ë•øÊù±‰∫¨„ÅÆ„Å©„Åì„Åã': None,
 'Roaming on  beaches': None,
 'Chicago, IL': ' United States',
 '€å⁄© ÿßÿ™ÿßŸÇ Ÿáÿ± ÿ¨ÿß ': None,
 'H√† N·ªôi, Vi·ªát Nam': ' Vietnam',
 'Hartford, CT': ' United States',
 'Berlin': ' Germany',
 'Kota Surabaya, Jawa Timur': ' Indonesia',
 'Earth ': ' United States',
 'tokyo': ' Japan',
 'Estonia': 'Estonia',
 'Bangladesh': 'Bangladesh',
 'Italy': 'Italy',
 'Á¶èÂ≤°Â∏ÇÂçöÂ§öÂå∫': ' Japan',
 'Budapest, Magyarorsz√°g': ' Hungary',
 'Web3': ' Kazakhstan',
 'Business ': ' United States',
 'Toronto, Ontario': ' Canada',
 'Sapele, Nigeria': ' Nigeria',
 'Los Angeles, CA': ' United States',
 'California, United States': ' United States',
 'Bali': ' Indonesia',
 'Medan Kota, Indonesia': ' Indonesia',
 'Liverpool, England': ' United Kingdom',
 'Leatherhead, South East': None,
 'Dubai, United Arab Emirates': ' United Arab Emirates',
 'On The Chain': ' Canada',
 'Prague': ' Czechia',
 'Porto Alegre, Brazil': ' Brazil',
 'Ucr√¢nia': 'Ukraine',
 'Sweden': 'Sweden',
 'France': 'France',
 'Italia': 'Italy',
 'Goa, India': ' India',
 'The Universe ': ' United States',
 'Raipur, India': ' India',
 'ÂåóÊµ∑ÈÅì': ' Japan',
 'Brasil': 'Brazil',
 'MEMELANDIA': None,
 'Argentina': 'Argentina',
 'USA': ' Japan',
 'wonderland.eth': ' South Africa',
 'Port Arthur': ' United States',
 'London': ' United Kingdom',
 'Sao Paulo, Brazil': ' Brazil',
 'Dubai ': ' United Arab Emirates',
 'www.pulsex.com': None,
 'Lagos Nigeria': ' Nigeria',
 'Smol Town': ' Lebanon',
 'Hyderabad, India': ' India',
 'Illinois, USA': ' United States',
 'Not financial advice': None,
 'Omnichain': None,
 'Abuja, Nigeria': ' Nigeria',
 'The Cathedral ': ' United States',
 'haarlem': ' Netherlands',
 'Cyberspace': ' Nigeria',
 'United States, California': ' United States',
 'The United States of America': ' United States',
 'Costa Rica': 'Costa Rica',
 'Subscribe üëâ': None,
 'Michigan': ' United States',
 'kerman.ir': ' Iran',
 'Springfield, VA': ' United States',
 '‰ªÆÊÉ≥ÈÄöË≤®„ÇÑNFT„ÇíÂ≠¶„Å∂„Å™„Çâ‚Üì': None,
 'Polkadot': ' United States',
 'Montreal, Quebec': ' Canada',
 'Ethereum': ' Ukraine',
 'on-chain': ' Canada',
 'London, England': ' United Kingdom',
 ' Orange ': ' United States',
 'Brazil': 'Brazil',
 'Naples': ' Italy',
 'MoonBase,TX': None,
 'Portharcourt': ' Nigeria',
 'Globetrotting ': None,
 'world': ' Ghana',
 'U.K.': 'United Kingdom',
 'nomad': ' United States',
 'Not Financial Advice': None,
 '‚ôö Rosmila Dewi F ‚ôö': None,
 'Brooklyn, NY': ' United States',
 'Japan': 'Japan',
 'McAllen, TX': ' United States',
 'Antarctica': 'Antarctica',
 'Stockholm Sweden': ' Sweden',
 'Littlerock': ' United States',
 'Mes liens üëá': None,
 ' Webster, NY ': ' United States',
 'Nashville, TN': ' United States',
 'Ukraine': 'Ukraine',
 'Japan Tokyo': ' Japan',
 ' National City': ' United States',
 'Outer Space': ' United Kingdom',
 'üáµüáπüá¨üáßüáßüá∑üá™üá¶üá®üáµüá∫üá∏üáØüáµ': None,
 'Heaven (maybe?)': None,
 '@bitcoin': ' Poland',
 'HK': ' China',
 'S√£o Jos√© do Rio Preto, Brasil': ' Brazil',
 'Êñ∞Âä†Âù°': ' Singapore',
 'Colorado, USA': ' United States',
 'Paris': ' France',
 'Somewhere on this plane': None,
 'Worldwide': ' Australia',
 'Port Harcourt, Nigeria': ' Nigeria',
 'Ireland': 'Ireland',
 'Read free newsletter  ‚ûô': None,
 'Vietnamese': ' Vietnam',
 'È¶ôÊ∏Ø': ' China',
 'Gaia': ' Romania',
 'Sampa': ' Burkina Faso',
 'Bear Island': ' Norway',
 'California, USA': ' United States',
 'The Metaverse': ' Australia',
 'Taxi Rank': ' South Africa',
 'Somewhere in my dreams': None,
 'Escondido': ' United States',
 'In The Lab‚úçüëâüëâ‚û°': ' South Korea',
 'Tphcm': ' Vietnam',
 'somewhere in this place': None,
 'Cheshire': ' United Kingdom',
 'Wales, United Kingdom': ' United Kingdom',
 'ÿßŸÑÿ•ŸÖÿßÿ±ÿßÿ™ ÿßŸÑÿπÿ±ÿ®Ÿäÿ© ÿßŸÑŸÖÿ™ÿ≠ÿØÿ©': 'United Arab Emirates',
 'Universe': ' Denmark',
 'web3': ' Kazakhstan',
 'üá™üá∏': None,
 'Mumbai': ' India',
 'Case Studiesüëâ': None,
 'In profits': ' India',
 'Punjab, Pakistan': ' Pakistan',
 'Adelaide, SA': ' Australia',
 'DE': ' United States',
 ' Rio Grande City, TX ': ' United States',
 'Viet Nam': 'Vietnam',
 'Êó•Êú¨ ÊÑõÁü•': ' Japan',
 'Viet Nam. ': 'Vietnam',
 'Jakarta': ' Indonesia',
 'Federal Capital Territory, Nig': None,
 'Bursa, T√ºrkiye': ' Turkey',
 'Kamienna G√≥ra, Polska': ' Poland',
 ' Norway ': 'Norway',
 'Cape Town, South Africa': ' South Africa',
 'I travel a lot ': None,
 ' Princeton, TX': ' United States',
 'The Interchain': None,
 'Bitcoin city': ' Poland',
 'New Hampshire': ' United States',
 'Silchar': ' India',
 'Jakarta Pusat, DKI JakartaüáÆüá©': ' Indonesia',
 'Lagos, Nigeria': ' Nigeria',
 '15% sale ‚û°Ô∏è TRADEALERT15  ': None,
 'Andromeda ': ' Italy',
 'H·ªì Ch√≠ Minh, Vi·ªát Nam': ' Vietnam',
 'Oregon (for now)': None,
 'Estados Unidos': 'United States',
 'A village by the lake': ' United States',
 'Hong Kong': ' China',
 'No affiliation with Binance': None,
 'üá¶üá∑': None,
 'Geochang-gun': ' South Korea',
 '„Åù„Åó„Å¶Êó•Êú¨Ë™û„ÇÇË©±„Åô„Çì„Å†ÔºÅ': None,
 'Washington DC': ' United States',
 'England, United Kingdom': ' United Kingdom',
 'The Orange Pill Book': None,
 'Arbitrum': None,
 'Eth, France': ' France',
 'Itaquaquecetuba': ' Brazil',
 'InvisibleLand': None,
 'Caracas, Venezuela': ' Venezuela',
 ' Stow, OH': ' United States',
 'Somewhere off Hexico': None,
 'ÂêçÂè§Â±ã': ' Japan',
 'DKI Jakarta, Indonesia': ' Indonesia',
 'Uyo, Nigeria': ' Nigeria',
 '‚Ç≥: $dr.bonzai': ' United States',
 'Helsinki': ' Finland',
 'US, Canada & India': ' United States',
 'Port-Harcourt': ' Nigeria',
 'Miami Seaquarium ': ' United States',
 'Dm for Promotion üö©': None,
 'echochamber': ' Switzerland',
 'Bonnyville, Alberta Canada': ' Canada',
 'Buffalo, New York': ' United States',
 'Victoria': ' Australia',
 'Paris, France': ' France',
 'Elgin, TX': ' United States',
 'tweets in üá™üá¶ / üá¨üáß': None,
 'FrenchisClub': None,
 'New Fang City': None,
 ' France Belgique UK': ' Algeria',
 'Sydney, New South Wales': ' Australia',
 'India': 'India',
 'Ecuador': 'Ecuador',
 'Space üöÄ': ' United States',
 'Guantanamo Bay ': ' Cuba',
 'ÎåÄÌïúÎØºÍµ≠ ÏÑúÏö∏': ' South Korea',
 'XRPL': None,
 'Stroudsburg, PA': ' United States',
 'Ê≠™ËÑñÂ±±': ' China',
 'North Palm Beach, FL': ' United States',
 'C√† Mau, Vietnam': ' Vietnam',
 '‚¨áÔ∏èMagicMonkey„ÅÆÔº∏„Çµ„Éº„ÇØ„É´ÂÖ•„ÇäÂè£„ÅØ„Åì„Å°„Çâ‚¨áÔ∏è': None,
 'An Engineer and Trader ': None,
 'Sydney, Australia': ' Australia',
 'Staking Land': None,
 'üá¨üáß': None,
 'T√ºrkiye': 'Turkey',
 'SIGN UP üëâ': ' United States',
 'Layer2': None,
 'Cronos': ' Argentina',
 'Cake Planet ùïè': ' Philippines',
 'Istanbul T√ºrkiye': ' Turkey',
 'Nigeria üá≥üá¨': 'Nigeria',
 'Follow Our Strategy Live üëâ': None,
 'OnTheWorld': None,
 'Waterford': ' Ireland',
 'Liverpool': ' United Kingdom',
 'üåê': None,
 'us': ' France',
 'metaverse': ' United States',
 'Bangkoküáπüá≠': ' Thailand',
 'Black and White': ' Poland',
 'Ho Chi Minh, Vietnam': ' Vietnam',
 "Let's Start Hereüëá": None,
 'United Arab Emirates': 'United Arab Emirates',
 'Republic of Korea': 'South Korea',
 'Kansas City': ' United States',
 '"Todos estamos conectados" ü§ù': None,
 'The Blockchain': None,
 '$0.00': ' Ecuador',
 'DeFi Fundamental Research': None,
 'Brickell - Miami, FL': ' United States',
 'Onchain': None,
 'ÂπøÂ∑û': ' China',
 'down in a hole': None,
 'The Abroad': ' Argentina',
 'Los Blockchain': None,
 'Á¶èÂª∫, ‰∏≠Âçé‰∫∫Ê∞ëÂÖ±ÂíåÂõΩ': ' China',
 'H√† N·ªôi': ' Vietnam',
 'Hell': ' United States',
 'Crypto Universe': None,
 ' Lowell, MA': ' United States',
 'Buenos Aires ARGENTINA': ' Italy',
 'Ê≤ñÁ∏Ñüå¥üå∫': ' Japan',
 'World': ' Ghana',
 'Wan Chai District, Hong Kong': ' China',
 'South Lyon': ' United States',
 'Osaka': ' Japan',
 ' Maine': ' United States',
 'Dallas Tx': ' United States',
 'Fort St. John': ' Canada',
 'fukuoka Japan': ' Japan',
 'San Antonio, TX': ' United States',
 'Amsterdam, NL': ' Netherlands',
 'Denver': ' United States',
 'K√∂ln, Deutschland': ' Germany',
 'Moon üåí': ' Estonia',
 'Serbia': 'Serbia',
 'Follow me': ' United States',
 'Vermillion, SD': ' United States',
 'Melbourne, Australia': ' Australia',
 'Chandigarh, India': ' India',
 'Usan, Scotland': ' United Kingdom',
 'Guadalajara, M√©xico': ' Mexico',
 'france': 'France',
 'this very paradise fire planet': None,
 'Hamburg': ' Germany',
 'Kava EVM': None,
 'Metaverso': None,
 'Mane,Net': ' India',
 'Jamaica': 'Jamaica',
 'Vietnam': 'Vietnam',
 'Slovak Rebublic, Bratislava': None,
 'Mundo Libre': ' Peru',
 'Owode, Nigeria': ' Nigeria',
 'Paris, Web3': None,
 'Manager‚Äôs special section': None,
 'ƒ∞stanbul': ' Turkey',
 'Paraguay': 'Paraguay',
 'Bogor Timur, Indonesia': ' Indonesia',
 'Crypto Education üá≥üá¨ üá¨üáß ': None,
 'Partner & CTO ‚Üí': None,
 'Selangor, Malaysia': ' Malaysia',
 'CryptoWorld': ' Germany',
 'Ciudad de Buenos Aires': ' Argentina',
 'Free Daily Market Update üëâ': None,
 '‰∏≠Âçé‰∫∫Ê∞ëÂÖ±ÂíåÂõΩ': 'China',
 'Baton Rouge, LA, USA': ' United States',
 'Interoperability': ' Italy',
 'Hydra': ' Greece',
 'Uniswap': None,
 'Multiverse ': ' United Kingdom',
 'Almeria': ' Spain',
 'meme': ' Cameroon',
 'Bangkok, Thailand': ' Thailand',
 'Martigny, Suisse': ' Switzerland',
 'Dragon Haven': ' South Africa',
 'Livorno, Tuscany': ' Italy',
 'Memeland IP Card Game üëâ': None,
 'New Zealand': 'New Zealand',
 'Nyon, Suisse': ' Switzerland',
 'ici': ' Fiji',
 'openseaüëÜ\u3000HEXAüëá': None,
 'Mauritania': 'Mauritania',
 'Stadtprozelten, Deutschland': ' Germany',
 'Naini Tal, India': ' India',
 'The Mystic PsyFam NFT HQ': None,
 'Trippie Island': None,
 'Pandora': ' United States',
 'Lincoln NE': ' United States',
 'Fidji': 'Fiji',
 'Salt Lake City, UT': ' United States',
 'SkyDome ': ' Canada',
 'Oslo': ' Norway',
 ' Ville Platte, LA ': ' United States',
 'Curitiba, PR': ' Brazil',
 'üìçWeb 3.0': ' Ethiopia',
 'Global South': ' Philippines',
 'Mumbai, India': ' India',
 'Tennessee, USA': ' United States',
 'Âè∞ÂåóÂ∏Ç, Âè∞ÁÅ£': ' Taiwan',
 'Join 9,000 readers ‚Üí': None,
 'Manhattan, NY': ' United States',
 'New Egypt, NJ': ' United States',
 '„Éà„É¨„Éë„É≥': None,
 'ÿß€åÿ±ÿßŸÜ': ' Iran',
 'Alfa clothing store': None,
 'Hanoi, Vietnam': ' Vietnam',
 'Kuwait.': 'Kuwait',
 'Munich': ' Germany',
 'Dallas, TX': ' United States',
 'HCMC': ' Vietnam',
 'Khusnul khotimah': ' Indonesia',
 'Tokyo-to, Japan': ' Japan',
 'Crypto University': ' Poland',
 '55044': ' United States',
 'SPACE': ' United States',
 'Dubai, UAE': ' United Arab Emirates',
 'Bangladesh ': 'Bangladesh',
 'Borno, Nigeria': ' Nigeria',
 'Nederland': 'Netherlands',
 ' Newburgh ': ' United States',
 'Nadela„ÄÇ': ' Spain',
 'Bozeman, MT': ' United States',
 'Cape Town ': ' South Africa',
 'Berlin, Germany': ' Germany',
 'jupiter': ' United States',
 'Solana': ' Philippines',
 'Saint Vincent and granadines': 'Saint Vincent and the Grenadines',
 '–†–æ—Å—Å–∏—è, ID: 989138': None,
 'ƒ∞stanbul, T√ºrkiye': ' Turkey',
 'Hallo': ' Turkey',
 'Clementinefurt': None,
 'Dhaka, Bangladesh': ' Bangladesh',
 'Bentleyville, OH': ' United States',
 'Cairo, Egypt': ' Egypt',
 'Poland': 'Poland',
 'WOO ': ' United States',
 'Â°ûÂ∞îÁª¥‰∫ö': 'Serbia',
 'Seychelles': 'Seychelles',
 'Build Wealth üíµ': None,
 'nha trang': ' Vietnam',
 'Leyer 2': ' Germany',
 'üëáüëâ': None,
 'Colombia|Chile|Argentina': None,
 '–£–∫—Ä–∞—ó–Ω–∞': ' Ukraine',
 'Topia': ' Mexico',
 'B·∫Øc Ninh, Vi·ªát Nam': ' Vietnam',
 'No affiliation with Reef': None,
 'Silicon Valley, US': ' United States',
 'Web3 DeFi Investment Fund': None,
 'The Moon, CA': ' United States',
 'VIET NAM': 'Vietnam',
 'Other Social Media Handles  ': None,
 ' London, KY': ' United States',
 'CryptoSpace': None,
 ' Mendota Heights ': ' United States',
 'Montreal': ' Canada',
 'The Netherlands': 'Netherlands',
 'Lets promote  eachother ': None,
 'All around the world': None,
 'USA, SC': ' United States',
 'Em algum Lugar de Lugar Nenhum': None,
 'Monaco': 'Monaco',
 '¬©Ô∏è2021 DeFi Money-Printerüñ®Ô∏èüí∞': None,
 'The netherlands': 'Netherlands',
 'DeadassvilleüóΩ': None,
 'H√©rault, Languedoc-Roussillon': ' France',
 'Lucky Numbers 135136 ‚Äì 135179': None,
 'Trader‚Ä¢Crypto‚Ä¢ASICMinner': None,
 'Bitcoin': ' Poland',
 'California, Us': ' United States',
 'Omnipresent': None,
 'Cardano Blockchain': None,
 'Linea‚õìÔ∏è': ' Italy',
 '‡§≠‡§æ‡§∞‡§§': 'India',
 'Europe': 'Europe',
 'Space': ' United States',
 'Renfrew, Scotland': ' United Kingdom',
 'Nelson': ' United States',
 'San Francisco, CA': ' United States',
 'Dhaka': ' Bangladesh',
 'New York': ' United States',
 'New York, NY': ' United States',
 'Lake Mckennabury': None,
 'decentralized': ' Greece',
 'Australia': 'Australia',
 'bitcoin': ' Poland',
 'Comment section': None,
 'Africa': 'Africa',
 'Hi! Jessie': ' United States',
 'UPDATE NEWS DAILY': None,
 'Otherside': ' United States',
 'Kodur, India': ' India',
 'Malaysia': 'Malaysia',
 'Oise, Picardie': ' France',
 'Ankara, T√ºrkiye': ' Turkey',
 'Paradise': ' United States',
 'üá≠üá∞': None,
 'NYC // WORLDWIDE': ' United States',
 'Twitter Spaces': None,
 'New Caledonia': ' France',
 'Detroit': ' United States',
 'El Salvador': 'El Salvador',
 'y6e6e6e6e6e': None,
 'Paris France': ' France',
 'RugDollz Island': None,
 'A Journey to Wonderous Hands ': None,
 'Cotonou, Benin': ' Benin',
 'Phoenix, AZ': ' United States',
 'Crypto': ' United States',
 'Hgtp://': None,
 'New Orleans, Louisiana': ' United States',
 'Croatia': 'Croatia',
 ' Indonesia üáÆüá©': 'Indonesia',
 'Athens, GR': ' Greece',
 'Los Santos #GTA': None,
 'crypto ': ' United States',
 '+8 Yƒ±l Teknik Analiz Tecr√ºbesi': None,
 'Spain': 'Spain',
 'Swiss': ' Lithuania',
 'NYC / Edinburgh / Bogota': None,
 'Dubai': ' United Arab Emirates',
 'Camp Degen': ' Switzerland',
 'Texas ': ' United States',
 'Stateless': None,
 'Sheridan, WY': ' United States',
 'Mars': ' France',
 'Texas': ' United States',
 'The Base': ' New Zealand',
 'New Brunswick, Canada': ' Canada',
 'Jungle': ' Uganda',
 'Th√°i B√¨nh, Vi·ªát Nam': ' Vietnam',
 'International': ' Czechia',
 'degenscore.com/profile/palmer': None,
 'Citizen of the World': None,
 '47 rue de Paradis 75010 Paris': ' France',
 'üåç': None,
 'Êó•Êú¨ Êù±‰∫¨': ' Japan',
 'Where Disruption Breathes': None,
 'Scotland': ' United Kingdom',
 'Amsterdam, Nederland': ' Netherlands',
 'NFT space': ' Israel',
 'Ohio, USA': ' United States',
 'Lisbon üáµüáπ': ' Portugal',
 'Ice Blue': ' Belgium',
 ' Manchester, MO ': ' United States',
 'San Salvador, El Salvador': ' El Salvador',
 '#UDverse': None,
 'L2 Developer': ' Poland',
 'Home': ' United States',
 'Binance': ' France',
 ' Poteau': ' United States',
 'Ph√∫ Th·ªç, Vi·ªát Nam': ' Vietnam',
 'Visioner': None,
 'DigiHub': ' Australia',
 'Minnesota, USA': ' United States',
 'üî≤': None,
 'Da Nang Viet Nam': ' Vietnam',
 'World Wide': ' United States',
 ' Gilberts, IL ': ' United States',
 'Building 2, Bldg, North London': None,
 'Cosmos': ' Brazil',
 'Cayman Islands': 'Cayman Islands',
 'Opensea': ' Italy',
 ' Franklin, WI': ' United States',
 'S√£o Paulo': ' Brazil',
 'Barcelona': ' Spain',
 'VietNam': 'Vietnam',
 'NY': ' United States',
 'Solana Beach, CA': ' United States',
 'Virginia, USA': ' United States',
 'S√†i G√≤n': ' Vietnam',
 'up there': ' United States',
 'ISS': ' Germany',
 'Venus': ' United States',
 "Man's Shire, UK ": ' United Kingdom',
 'Barranquilla colombia': ' Colombia',
 'Sri Lanka': 'Sri Lanka',
 'Canada in view ': None,
 'Lake Izabellashire': None,
 'Training Grounds': ' South Africa',
 'Netherlands': 'Netherlands',
 'omniverse': None,
 'Crypto Nation': None,
 'loading‚Ä¶': ' United States',
 'Detroit, MI/ Columbia, SC': None,
 'Berlin, Deutschland': ' Germany',
 'Iowa': ' United States',
 'crypto eth': None,
 'Bayo Kuku Rd, Ikoyi 106104, La': ' Nigeria',
 'Rossville, TN': ' United States',
 'Rennes, France': ' France',
 'Starknet': None,
 'Anywhere But Here': None,
 'NFT Spaces': None,
 'Êù±‰∫¨ Ê±üÊù±Âå∫': ' Japan',
 'Ê∑±Âú≥': ' China',
 'Online': ' France',
 'Bretagne': ' France',
 'Germany': 'Germany',
 'Metaverse ': ' United States',
 'Batsari, Nigeria': ' Nigeria',
 'In my truck.': None,
 'Visegrad': ' Bosnia and Herzegovina',
 'Remote': ' United States',
 'Tele: @Noma1219 ': None,
 'CryptoLand': None,
 'Belgrade, Republic of Serbia': ' Serbia',
 'METAVERS ': None,
 'Lowell': ' United States',
 'Planet X': ' United Kingdom',
 'Earth, Milky Way.': None,
 'Idaho Mountains': ' United States',
 'Degen world üíé': None,
 'Anambra state': ' Nigeria',
 'Suisse': ' France',
 'Madrid Spain': ' Philippines',
 'Almanya': 'Germany',
 'Buenos Aires, Argentina': ' Argentina',
 'Jharsuguda, India': ' India',
 'Einstein HQ ': ' Israel',
 '57529.bitmap': ' Ghana',
 'On Stolen Land': None,
 'My Own World': ' United States',
 'Hiller√∏d, Danmark': ' Denmark',
 'St. Petersburg, FL': ' United States',
 'Discord-0xlords#4669': None,
 'Diaspora': ' Kosovo',
 'Algeria': 'Algeria',
 'Liberia': 'Liberia',
 'Bangalore, India': ' India',
 'Graveyard': ' Barbados',
 'Dublin City, Ireland': ' Ireland',
 'On Chain': ' Canada',
 'Calgary, Alberta': ' Canada',
 'BUY NOIA on Kucoin  ‚û°Ô∏è': None,
 'South East, England': ' United Kingdom',
 'ËÑ≥Ê±Å„Çµ„É≠„É≥': None,
 'ES | FR | IT': None,
 '$CORE': ' United States',
 'Solana realm': None,
 'HongKong': ' China',
 'Alone, with you': None,
 'CAWMmunity': None,
 '„ÅÇ„Å™„Åü„ÅÆÈö£': None,
 'Russia': 'Russia',
 'Shitting in your closet': None,
 'Las Vegas': ' United States',
 'Houston | She / Her üè≥Ô∏è\u200d‚ößÔ∏è| 19': None,
 'Pittsburgh, PA': ' United States',
 'East Hampton, NY': ' United States',
 'Pennsylvania': ' United States',
 'Miannay ': ' France',
 'Pompano Beach': ' United States',
 'Layer 2': ' Germany',
 'Houston, TX': ' United States',
 'Prestige World Wide': None,
 'Neptune': ' United States',
 'Kerala, India': ' India',
 'üÜÉüÖ∏üÖºüÖ¥üÖ≤üÖ∑üÖ∞üÖ∏üÖΩ': None,

In [235]:
country = []
for i in range(users.shape[0]):
    k = users["location"][i]
    if k == "" or str(k) == "nan":
        country.append(None)
    else:
        v = location_dict[k]
        if isinstance(v, str):
            v = v.strip()
        country.append(v)
users["country"] = country
users["country"].unique()

array([None, 'United States', 'Japan', 'Italy', 'United Kingdom',
       'Venezuela', 'Estonia', 'Vietnam', 'Belgium', 'Canada', 'Nigeria',
       'Portugal', 'Tanzania', 'Switzerland', 'Central African Republic',
       'Netherlands', 'Argentina', 'Australia', 'Kazakhstan', 'Greece',
       'Philippines', 'Algeria', 'Ukraine', 'Norway', 'India', 'France',
       'Colombia', 'Singapore', 'Indonesia', 'Romania', 'Taiwan',
       'Germany', 'Bangladesh', 'Hungary', 'United Arab Emirates',
       'Czechia', 'Brazil', 'Sweden', 'South Africa', 'Lebanon',
       'Costa Rica', 'Iran', 'Ghana', 'Antarctica', 'Poland', 'China',
       'Ireland', 'Burkina Faso', 'South Korea', 'Denmark', 'Pakistan',
       'Turkey', 'Finland', 'Ecuador', 'Cuba', 'Thailand', 'Serbia',
       'Mexico', 'Jamaica', 'Peru', 'Paraguay', 'Malaysia', 'Spain',
       'Cameroon', 'New Zealand', 'Fiji', 'Mauritania', 'Ethiopia',
       'Kuwait', 'Saint Vincent and the Grenadines', 'Egypt',
       'Seychelles', 'Monaco', 'Europe', 'Africa', 'El Salvador', 'Benin',
       'Croatia', 'Lithuania', 'Uganda', 'Israel', 'Cayman Islands',
       'Sri Lanka', 'Bosnia and Herzegovina', 'Kosovo', 'Liberia',
       'Barbados', 'Russia', 'Palestinian Territories', 'North Pole',
       'Kenya', 'Luxembourg', 'Malta', 'Georgia', 'Belize',
       'Ascension and Tristan da Cunha', 'Morocco',
       'British Virgin Islands', 'Tajikistan', 'Gornja Siga', 'Burundi',
       'Liechtenstein', 'Jordan'], dtype=object)

In [236]:
missing_cnt = {
    "Kosovo": "Europe",
    "Palestinian Territories": "Asia",
    "North Pole": "Arctic",
    "Ascension and Tristan da Cunha": "Africa",
    "Gornja Siga": "Europe"
}

def country_to_continent(country_name: str) -> str:
    try:
        country_alpha = pc.country_name_to_country_alpha2(country_name)
        country_continent_code = pc.country_alpha2_to_continent_code(country_alpha)
        country_continent_name = pc.convert_continent_code_to_continent_name(country_continent_code)
        return country_continent_name
    except:
        if country_name in ["Europe", "Africa", "Antarctica"]:
            return country_name
        return missing_cnt[country_name]

for i, x in enumerate(country):
    if x is not None:
        country[i] = country_to_continent(x)
    else:
        country[i] = None

In [237]:
users_dropped["location"] = country
users_dropped["location"].unique()

array([None, 'North America', 'Asia', 'Europe', 'South America', 'Africa',
       'Oceania', 'Antarctica', 'Arctic'], dtype=object)

In [238]:
users_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2150 entries, 0 to 2149
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2149 non-null   float64
 1   username         2149 non-null   object
 2   followersCount   2149 non-null   float64
 3   friendsCount     2149 non-null   float64
 4   statusesCount    2149 non-null   float64
 5   favouritesCount  2149 non-null   float64
 6   listedCount      2149 non-null   float64
 7   mediaCount       2149 non-null   float64
 8   location         1000 non-null   object
 9   verified         2149 non-null   object
 10  blue             2149 non-null   object
dtypes: float64(7), object(4)
memory usage: 266.1+ KB

# PREPROCESSING

In [262]:
# drop null label + drop verified (full False) + encode blue
#users_processed = users_dropped[users_dropped["location"].notnull()]
users_processed = users_dropped.drop(columns=["verified"], axis=1)
users_processed.dropna(subset=users_processed.columns.difference(["location"]), inplace=True)

users_processed.rename(columns={"id": "user_id"}, inplace=True)
users_processed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2149 entries, 0 to 2149
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          2149 non-null   float64
 1   username         2149 non-null   object
 2   followersCount   2149 non-null   float64
 3   friendsCount     2149 non-null   float64
 4   statusesCount    2149 non-null   float64
 5   favouritesCount  2149 non-null   float64
 6   listedCount      2149 non-null   float64
 7   mediaCount       2149 non-null   float64
 8   location         1000 non-null   object
 9   blue             2149 non-null   object
dtypes: float64(7), object(3)
memory usage: 184.7+ KB

In [263]:
# drop null + avg count by user
tweets_processed = tweets_dropped.drop(columns=["id"], axis=1)
tweets_processed = tweets_processed.dropna()
tweets_processed = tweets_processed.groupby(["user_id"]).mean().reset_index()
tweets_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13147 entries, 0 to 13146
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       13147 non-null  int64
 1   replyCount    13147 non-null  float64
 2   retweetCount  13147 non-null  float64
 3   likeCount     13147 non-null  float64
 4   quoteCount    13147 non-null  float64
 5   viewCount     13147 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 616.4 KB

In [268]:
# merge data
data = pd.merge(users_processed, tweets_processed, how='left', on=['user_id'])
data[tweets_processed.columns.difference(["user_id"])] = data[tweets_processed.columns.difference(["user_id"])].fillna(0)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          2149 non-null   float64
 1   username         2149 non-null   object
 2   followersCount   2149 non-null   float64
 3   friendsCount     2149 non-null   float64
 4   statusesCount    2149 non-null   float64
 5   favouritesCount  2149 non-null   float64
 6   listedCount      2149 non-null   float64
 7   mediaCount       2149 non-null   float64
 8   location         1000 non-null   object
 9   blue             2149 non-null   object
 10  replyCount       2149 non-null   float64
 11  retweetCount     2149 non-null   float64
 12  likeCount        2149 non-null   float64
 13  quoteCount       2149 non-null   float64
 14  viewCount        2149 non-null   float64
dtypes: float64(12), object(3)
memory usage: 252.0+ KB

# ML

In [183]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [203]:
data = data[data["location"] != "Arctic"]
data["location"].unique()
data["blue"] = data["blue"].astype("object")

In [271]:
isinstance(data["location"], pd.Series)

True

In [204]:
cat_attrbs = data.select_dtypes(include="object").columns.tolist()[2:]
num_attrbs = data.select_dtypes(exclude="object").columns.tolist()[1:]
cat_attrbs

['blue']

In [206]:
fn = ColumnTransformer([
    ("std_scaler", StandardScaler(), num_attrbs),
    ("lbl_encoder", OrdinalEncoder(), cat_attrbs),
], remainder="drop")
pipe = Pipeline([
    ("preprocess_fn", fn),
])
X_train = pipe.fit_transform(data.drop(columns=["location"], axis=1))
lb_encoder = LabelEncoder()
y_train = lb_encoder.fit_transform(data["location"])

In [274]:
LABEL_MAP = {
    'Africa': 0, 
    'Antarctica': 1, 
    'Asia': 2, 
    'Europe': 3, 
    'North America': 4,
    'Oceania': 5, 
    'South America': 6,
    'Arctic': 7
}
data["location"].map(LABEL_MAP).to_numpy()

array([nan,  4.,  2., ...,  2., nan, nan])

In [207]:
import numpy as np
np.unique(y_train, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6]),
 array([ 83,   2, 272, 243, 333,  30,  36], dtype=int64))

In [188]:
lb_encoder.classes_

array(['Africa', 'Antarctica', 'Asia', 'Europe', 'North America',
       'Oceania', 'South America'], dtype=object)

In [223]:
rf_clf = RandomForestClassifier(n_estimators=95, 
                                max_depth=10,
                                random_state=42)
cross_val_score(rf_clf, X_train, y_train, scoring="roc_auc_ovo", cv=2, n_jobs=-1).mean()

0.6444714177223176

In [224]:
import joblib
import os

rf_clf.fit(X_train, y_train)
joblib.dump(rf_clf, os.path.join("D:\Projects\Big data storage and processing\IT4043E_Group15_Problem1\output\models", "rf-n_estimators_95-max_depth_11.pkl"))

['D:\\Projects\\Big data storage and processing\\IT4043E_Group15_Problem1\\output\\models\\rf-n_estimators_95-max_depth_11.pkl']

In [210]:
svm_clf = SVC(C=2.26, kernel="rbf", decision_function_shape="ovo", probability=True, random_state=42)
cross_val_score(svm_clf, X_train, y_train, scoring="roc_auc_ovo", cv=2, n_jobs=-1).mean()

0.5328777114265784